#!/usr/bin/env python3
r"""
Build a concise Word document from scraped NGA posts.

Usage:
  python .\build_wolf_june_doc.py .\wolf_posts.json --out .\wolf_june_posts.docx

The input JSON should be generated by scrape_nga_user_thread.py. Posts are
filtered to June by default and grouped into Monday-Sunday week sections.
"""

from __future__ import annotations

import argparse
import json
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any

from docx import Document
from docx.enum.section import WD_SECTION_START
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml import OxmlElement
from docx.oxml.ns import qn
from docx.shared import Pt, RGBColor


@dataclass
class NormalizedPost:
    floor: str
    posted_at_text: str
    posted_at: datetime
    body: str
    page: int | None
    url: str


def parse_post_time(value: str, fallback_year: int | None) -> datetime | None:
    text = value.strip()
    if not text:
        return None

    candidates = [
        r"(?P<year>\d{4})[-/年.](?P<month>\d{1,2})[-/月.](?P<day>\d{1,2})日?\s*(?P<hour>\d{1,2})?:?(?P<minute>\d{1,2})?",
        r"(?P<month>\d{1,2})[-/月.](?P<day>\d{1,2})日?\s*(?P<hour>\d{1,2})?:?(?P<minute>\d{1,2})?",
    ]

    for pattern in candidates:
        match = re.search(pattern, text)
        if not match:
            continue
        groups = match.groupdict()
        year_text = groups.get("year")
        year = int(year_text) if year_text else fallback_year
        if year is None:
            continue
        month = int(groups["month"])
        day = int(groups["day"])
        hour = int(groups.get("hour") or 0)
        minute = int(groups.get("minute") or 0)
        try:
            return datetime(year, month, day, hour, minute)
        except ValueError:
            return None
    return None


def clean_body(value: str) -> str:
    text = value.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"\[/?(?:quote|collapse|b|i|u|url|img|color|size)[^\]]*\]", "", text, flags=re.I)
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def load_posts(path: Path, month: int, year: int | None) -> tuple[list[NormalizedPost], list[dict[str, Any]]]:
    raw_posts = json.loads(path.read_text(encoding="utf-8-sig"))
    posts: list[NormalizedPost] = []
    skipped: list[dict[str, Any]] = []

    for item in raw_posts:
        posted_at_text = str(item.get("time") or "")
        parsed_time = parse_post_time(posted_at_text, year)
        if parsed_time is None:
            skipped.append(item)
            continue
        if parsed_time.month != month:
            continue
        if year is not None and parsed_time.year != year:
            continue

        body = clean_body(str(item.get("body") or ""))
        if not body:
            continue
        posts.append(
            NormalizedPost(
                floor=str(item.get("floor") or ""),
                posted_at_text=posted_at_text,
                posted_at=parsed_time,
                body=body,
                page=item.get("page"),
                url=str(item.get("url") or ""),
            )
        )

    posts.sort(key=lambda post: (post.posted_at, post.floor))
    return posts, skipped


def week_start(day: date) -> date:
    return day - timedelta(days=day.weekday())


def week_label(start: date, month: int) -> str:
    end = start + timedelta(days=6)
    clipped_start = max(start, date(start.year, month, 1))
    if month == 12:
        next_month = date(start.year + 1, 1, 1)
    else:
        next_month = date(start.year, month + 1, 1)
    clipped_end = min(end, next_month - timedelta(days=1))
    return f"{clipped_start:%m月%d日} - {clipped_end:%m月%d日}"


def group_by_week(posts: list[NormalizedPost]) -> dict[date, list[NormalizedPost]]:
    grouped: dict[date, list[NormalizedPost]] = defaultdict(list)
    for post in posts:
        grouped[week_start(post.posted_at.date())].append(post)
    return dict(sorted(grouped.items(), key=lambda item: item[0]))


def set_cell_shading(cell: Any, fill: str) -> None:
    tc_pr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:fill"), fill)
    tc_pr.append(shd)


def add_post(document: Document, post: NormalizedPost) -> None:
    table = document.add_table(rows=2, cols=1)
    table.style = "Table Grid"
    header = table.rows[0].cells[0]
    set_cell_shading(header, "EEF2F7")
    meta = header.paragraphs[0]
    meta.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = meta.add_run(f"{post.floor or '未知楼层'}  |  {post.posted_at_text}")
    run.bold = True
    run.font.size = Pt(10)
    run.font.color.rgb = RGBColor(31, 41, 55)

    body_cell = table.rows[1].cells[0]
    body_paragraph = body_cell.paragraphs[0]
    body_paragraph.paragraph_format.space_after = Pt(0)
    for index, paragraph_text in enumerate(post.body.split("\n\n")):
        paragraph = body_paragraph if index == 0 else body_cell.add_paragraph()
        paragraph.paragraph_format.line_spacing = 1.2
        paragraph.paragraph_format.space_after = Pt(6)
        for line_index, line in enumerate(paragraph_text.split("\n")):
            if line_index:
                paragraph.add_run().add_break()
            text_run = paragraph.add_run(line.strip())
            text_run.font.size = Pt(10.5)

    document.add_paragraph()


def style_document(document: Document) -> None:
    section = document.sections[0]
    section.top_margin = Pt(56)
    section.bottom_margin = Pt(56)
    section.left_margin = Pt(60)
    section.right_margin = Pt(60)

    styles = document.styles
    styles["Normal"].font.name = "Microsoft YaHei"
    styles["Normal"]._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
    styles["Normal"].font.size = Pt(10.5)

    for style_name, size, color in [
        ("Title", 22, "111827"),
        ("Heading 1", 16, "111827"),
        ("Heading 2", 13, "374151"),
    ]:
        style = styles[style_name]
        style.font.name = "Microsoft YaHei"
        style._element.rPr.rFonts.set(qn("w:eastAsia"), "Microsoft YaHei")
        style.font.size = Pt(size)
        style.font.color.rgb = RGBColor.from_string(color)


def build_docx(posts: list[NormalizedPost], output_path: Path, month: int, source_path: Path) -> None:
    document = Document()
    style_document(document)

    title = document.add_paragraph()
    title.style = document.styles["Title"]
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.add_run(f"狼大 {month} 月发言整理")

    subtitle = document.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    subtitle_run = subtitle.add_run(f"来源：{source_path.name}  |  共 {len(posts)} 条")
    subtitle_run.font.size = Pt(10)
    subtitle_run.font.color.rgb = RGBColor(107, 114, 128)

    document.add_paragraph()
    grouped = group_by_week(posts)
    for index, (start, week_posts) in enumerate(grouped.items(), start=1):
        if index > 1:
            document.add_section(WD_SECTION_START.NEW_PAGE)
        heading = document.add_heading(f"第 {index} 周：{week_label(start, month)}", level=1)
        heading.paragraph_format.space_after = Pt(8)
        summary = document.add_paragraph()
        summary_run = summary.add_run(f"本周共 {len(week_posts)} 条发言")
        summary_run.font.size = Pt(10)
        summary_run.font.color.rgb = RGBColor(107, 114, 128)

        for post in week_posts:
            add_post(document, post)

    document.save(output_path)


def write_markdown(posts: list[NormalizedPost], output_path: Path, month: int) -> None:
    lines = [f"# 狼大 {month} 月发言整理", ""]
    for index, (start, week_posts) in enumerate(group_by_week(posts).items(), start=1):
        lines.append(f"## 第 {index} 周：{week_label(start, month)}")
        lines.append("")
        for post in week_posts:
            lines.append(f"### {post.floor or '未知楼层'} | {post.posted_at_text}")
            lines.append("")
            lines.append(post.body)
            lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a weekly Word digest for wolf's June NGA posts.")
    parser.add_argument("input_json", help="JSON produced by scrape_nga_user_thread.py.")
    parser.add_argument("--out", default="wolf_june_posts.docx", help="Output .docx path.")
    parser.add_argument("--month", type=int, default=6, help="Month to include. Defaults to 6.")
    parser.add_argument("--year", type=int, help="Optional year filter; also used when NGA time lacks a year.")
    parser.add_argument("--markdown", help="Optional Markdown mirror path.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    input_path = Path(args.input_json)
    output_path = Path(args.out)
    markdown_path = Path(args.markdown) if args.markdown else output_path.with_suffix(".md")

    posts, skipped = load_posts(input_path, args.month, args.year)
    if not posts:
        print("No matching posts found. Check the input JSON date format or pass --year.", flush=True)
        if skipped:
            print(f"Skipped {len(skipped)} posts because their timestamps could not be parsed.", flush=True)
        return 1

    build_docx(posts, output_path, args.month, input_path)
    write_markdown(posts, markdown_path, args.month)
    print(f"Saved {len(posts)} posts to {output_path}")
    print(f"Markdown mirror saved to {markdown_path}")
    if skipped:
        print(f"Skipped {len(skipped)} posts with unparseable timestamps.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
